---
driver_plugin: vagrant

driver_config:
  customize:
    memory: 1024

platforms:
- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: http://opscode-vm.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_chef-11.2.0.box
    require_chef_omnibus: 11.4.0
- name: centos-6.3
  driver_config:
    box: opscode-centos-6.3
    box_url: http://opscode-vm.s3.amazonaws.com/vagrant/opscode_centos-6.3_chef-11.2.0.box
    require_chef_omnibus: 11.4.0

suites:
- name: default
  run_list:
  - recipe[minitest-handler]
  - recipe[stash_test]
  attributes: {}
- name: apache2
  run_list:
  - recipe[minitest-handler]
  - recipe[stash_test::apache2]
  attributes: {}
